# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEIrlBIfA6KymgSQ2J7fiqEtiXr5IPG8
"""

import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

df_titanic = sns.load_dataset('titanic')

print(df_titanic.info())
print(df_titanic.isna().sum())
#As passoas com a passagem (pclass) mais cara, sobreviveram mais do que as com ingressos mais baratas?

media_aparada = stats.trim_mean(df_titanic['age'].dropna(), 0.1)
df_titanic['age'] = df_titanic['age'].fillna(media_aparada)

nome = [(df_titanic['embark_town'] == 'Cherbourg'), (df_titanic['embark_town'] == 'Southampton'), (df_titanic['embark_town'] == 'Queenstown')]
sigla_cidadeEmbacarda =['C', 'S', 'Q']

df_titanic['embarked'] = np.select(nome, sigla_cidadeEmbacarda, default='Não Informado')
df_titanic['embark_town'] = df_titanic['embark_town'].fillna('Não Informado')

df_titanic['deck'] = df_titanic['deck'].astype(str).fillna('Não Informado')

print(df_titanic.describe())

print(df_titanic.head())

corr = df_titanic.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.show()

plt.figure(figsize=(5, 4))
sns.boxplot(x='class',
            y='age',
            data=df_titanic)

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.title('Distribuição da idade dos passageiros pela classe', pad=20)
plt.xlabel('Classe do passageiro', labelpad=10)
plt.ylabel('idade', labelpad=10)

plt.show()

plt.figure(figsize=(5, 4))
sns.boxplot(x='class',
            y='fare',
            data=df_titanic)

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.title('Distribuição da tarifa dos passageiros pela classe', pad=20)
plt.xlabel('Classe do passageiro', labelpad=10)
plt.ylabel('Valor da tarifa', labelpad=10)

plt.show()

plt.figure(figsize=(5, 4))
sns.countplot(x='class', data=df_titanic[df_titanic['survived'] == 1], hue='class')

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['left'].set_visible(False)
plt.xlabel('Classe do passageiro', labelpad=10)
plt.ylabel('')
plt.yticks([])
plt.title("Quantidade de sobreviventes por classe", pad=20)

for spine in plt.gca().spines.values():
  spine.set_visible(False)

for container in plt.gca().containers:
  plt.gca().bar_label(container, padding=3, fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()

print(df_titanic.groupby('class')['survived'].mean())

plt.figure(figsize=(5, 4))
sns.boxplot(x='sex',
            y='age',
            data=df_titanic, hue='class')

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.title('Distribuição da idade dos passageiros pelao sexo', pad=20)
plt.xlabel('Sexo do passageiro', labelpad=10)
plt.ylabel('idade', labelpad=10)

plt.show()

plt.figure(figsize=(5, 4))
sns.boxplot(x='sex',
            y='fare',
            data=df_titanic, hue='class')

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.title('Distribuição da tarifa dos passageiros pelo sexo', pad=20)
plt.xlabel('Sexo do passageiro', labelpad=10)
plt.ylabel('Valor da tarifa', labelpad=10)

plt.show()

plt.figure(figsize=(5, 4))
sns.countplot(x='sex', data=df_titanic[df_titanic['survived'] == 1], hue='class')

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['left'].set_visible(False)
plt.xlabel('Sexo do passageiro', labelpad=10)
plt.ylabel('')
plt.yticks([])
plt.title('Quantidade de sobreviventes por sexo em relação a classe', pad=20)
for spine in plt.gca().spines.values():
  spine.set_visible(False)

for container in plt.gca().containers:
  plt.gca().bar_label(container, padding=3, fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()

print(df_titanic.groupby('sex')['survived'].mean())